### ISSUE TITLE
테이블 명을 소문자로 할 것인가 대문자로 할 것인가?

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#14]
https://github.com/woowacourse-moltudy/15-mins-retrospective/pull/12/files/649d31e301bfae66d5d62df438071ca26d271af3#r648438946

위와 같은 이유로, ddl작성 시 테이블명의 대소문자 컨벤션을 정해야 할 것 같습니다.
소문자면 sql문도 소문자로 작성하도록..

**Comment by sihyung92** [comment]
훔 가급적 에러가 안 나는 상황으로 가고 싶은데 어떻게 해야 DB간 포팅이 쉬울까요? 
sql문에서의 대소문자 구분은 가독성을 위한 컨벤션인데 어떤 게 좋은지 의논해보면 좋을거같네요

**Comment by bperhaps** [comment]
레거시의 sql컨벤션을 지키고 싶다면, 테이블명을 대문자로 통일하면 간단하게 해결될듯 합니당
