### ISSUE TITLE
Exception 구분

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#15]
custom exception을 사용하기로 하였으나, 공통 exception에 대한 논의가 이루어 지지 않았음.

**Comment by sihyung92** [comment]
공통 exception은 무얼 의미하나요? RuntimeException을 상속하는 부모예외객체를 만들자는 뜻인가요?

**Comment by bperhaps** [comment]
것보다는, 서로 다른 도메인에서 공통으로 사용될 예외가 분명 있을거라 생각돼요 예를들면 뭐 잘못된 접근예외 이런게 있으면 모든 도메인마다 잘못된 접근예외를 각자 만들어쓰는거 이상하다 생각해서 이런거를 공통적으로 만들어 쓰는게ㅜ좋다는 생각입니다~

**Comment by sihyung92** [comment]
아하 그런 의미 였군요 회의에서 논의해보면 좋을 것 같습니다
