### ISSUE TITLE
DAO vs Repository

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#16]
Dao를 사용할지 Repository를 사용할지에 대한 논의가 이루어 지지 않았음.

**Comment by sihyung92** [comment]
Dao를 활용할 것을 주장합니다 기본 모델을 subway-map, subway-path 모델을 따라가기로 했는데 해당 미션에선 repository를 구현해보고 느낀점은 지금 단계에선 불필요하다는 점이었습니다. Dao를 bypass하는 로직 이상의 역할이 없었거든요. repository가 필요한 이유에 대해서 설명해주시면 회의 주제로 올리겠습니다

**Comment by bperhaps** [comment]
일단, 객체 자체를 영속성 모델로 보낼 수 있다는 점 하나로 모든게 설명 가능하다 느끼고, dao를 사용하면 데이터 관련 검증들을 db에 의존하게 되는 로직이 짜여지는 것 같아요.
그리고　repository가 dao의 바이패스로 느낀건 개인적인 생각이지만 잘못된 접근으로 기술을 사용한 것 아니었나.. 하고 조심스래 의견 드려봅니다...

**Comment by sihyung92** [comment]
혹시 미션에세 레포지토리를 사용하거나 개인 프로젝트에서 레포지토리를 활용한 사례가 있나요? 현재 미션에서도 대부분 크루가 Dao에 도메인 객체를 보내고 도메인 객체로 반환 받는 방식을 사용하고 있는데 이건 `객체를 영속성 모델로 보낸다` 아닌가요? 실제로 활용한 사례를 봐야 이해가 될 것 같습니다

**Comment by bperhaps** [comment]
- 예전 지하철 미션에서 간단하게나마 Repository를 구현한 것, Domain레이어에 Repository의 interface가 있는 부분을 봐야합니다.
https://github.com/bperhaps/atdd-subway-map/tree/step3/src/main/java/wooteco/subway/infrastructure/line

- 예전에 블로그에 쓴 글. 둘의 차이점도 알아보면 좋을듯요
https://bperhaps.tistory.com/entry/Repository와-Dao의-차이점

**Comment by sihyung92** [comment]
냥냥펀치
