### ISSUE TITLE
왜 fork형식이 아니라 본 repository에서 브랜치를 분리하는건가요?

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#17]
아까 회의에서는 그러려니 넘어갔는데 생각할수록 이해가 안되는 것 같아요.
관련 브랜칭 전략이 있는건가요?

**Comment by sihyung92** [comment]
https://nvie.com/posts/a-successful-git-branching-model/
해당 모델 중 기능 브랜치 부분만 따서 진행하고 있습니당(실제 운영상황이 아니므로)
기능 브랜치를 메인 레포에서 별도로 구현하여 활용하는 이유에 대해선
1. 기능 브랜치를 개인 포크 레포지토리에서 진행하면 다른 사람이 진행여부를 확인하기위해 개인 포크 레포지토리를 찾아가서 확인해야 합니다. 로컬에서 해당 기능을 확인하기 위해서 각 개발자 레포의 remote를 등록해야하는 번잡함이 생깁니다.
2. 해당 기능(A)에서 파생한 기능(A-1)을 구현하려는 사람이 생기면 메인레포에 기능 브랜치가 있어야 해당 기능브랜치를 베이스로 작업을 진행할 수 있습니다.
3. 한 기능을 여러 명이 작업해야 하는 상황도 대처할 수 있습니다.

생각나는 이점은 이정도가 있네요 그에 비해 비용은 브랜치를 생성하고 관리해야한다 정도 이므로(브랜치를 샌드박스처럼 활용하고 싶다면 그때 포크레포지토리를 활용하면 될 것같습니다), 실보다 득이 많은 전략이라고 생각합니다

**Comment by bperhaps** [comment]
오호.. 메인 레포가 많이 더러워질것 같은 걱정보다는 득이 많은 전략이었네요!! 감사합니다 :)
