### ISSUE TITLE
주생성자 - 부생성자 순보다 부생성자 - 주생성자 순으로 작성하는 게 더 자연스러운 것 같아요!

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#18]
주생성자 - 부생성자 순보다 부생성자 - 주생성자 순으로 작성하는 게 더 자연스러운 것 같아요!

__Originally posted by @da-nyee in https://github.com/woowacourse-moltudy/15-mins-retrospective/pull/10#discussion_r648535741__

컨벤션 정하죠!?? 저는 항상 주-부 였는데 부-주 의견이 있네요?

**Comment by sihyung92** [comment]
전 항상 부 - 주 입니다 제가 느끼기엔 호출받는 메소드가 아래쪽에 있는 것이 편안해서요 
하지만 팀 컨벤션이 우선이라는 입장이기 때문에 정하면 좋을거 같네요
투표로 정하면 어떨까요 혹은 토론방식도 좋습니다

**Comment by bperhaps** [comment]
토론은 너무 길어질 것 같아서 투표가 편할 것 같기두 하구..
