### ISSUE TITLE
ObjectMapper를 위한 기본 생성자를 사용할 것인가?

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#25]
jackson mapper의 바인딩을 위해서 기본생성자를 만드는 것은 좋지만, 이런 경우 불변성이 깨지는점 때문에 저는 별로 좋아하지 않아요. ConstructorProperties나 JsonProperties를 고려해 보는건 어때요? 
아니면 이 사안을 이슈로 등록해주세요!

_Originally posted by @bperhaps in https://github.com/woowacourse-moltudy/15-mins-retrospective/pull/24#discussion_r649567904_

**Comment by sihyung92** [comment]
전 기본생성자 1표임돠 기본 생성자가 있었을 때 생길 문제상황이 뭐가 있을까요? 필드이름과 JSON으로 직렬화 시켜야할 이름이 다른 케이스에만 JsonProperty를 도입하는건 어떨까여?

**Comment by bperhaps** [comment]
흠.... 빈 객체를 만들 위험이 있다..? 흠... request는 그렇다 쳐도 response는 불변 유지시켰음 좋겠는디

**Comment by da-nyee** [comment]
저도 기본 생성자 1표요 !

손너잘이 말하는 `빈 객체를 만들 위험이 있다`는 기본 생성자를 public이 아닌 private으로 선언하면 해결할 수 있는 문제라고 생각합니다.
리플렉션은 접근 제어자가 상관 없기도 하고, 방금 private으로 변경하고 테스트 실행해봤는데 에러 없이 잘 통과합니다 !

**Comment by bperhaps** [comment]
@da-nyee 오 그런 방법이 있군요!! 최고에요! 감사합니다!! 이슈는 닫도록 하겠습니다!
