### ISSUE TITLE
테스트 이름에 대한 컨벤션.

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#26]
테스트 이름에 대한 컨벤션 이슈로 등록하겠습니다.

_Originally posted by @bperhaps in https://github.com/woowacourse-moltudy/15-mins-retrospective/pull/24#discussion_r649587450_

Test의 메서드 이름 작성시 컨벤션 어떻게 하시나요?
저는 

[테스트할 메서드 이름]_[테스트 내용]

식의 컨벤션을 주로 사용합니다(벨덩형님 컨벤션)
의논이 필요해 보입니다.

**Comment by sihyung92** [comment]
본문 내용에 동의입니다~~

**Comment by da-nyee** [comment]
저는 정상 케이스는 {테스트할 메소드 이름}으로, 예외 케이스는 {테스트할 메소드 이름 + Exception}으로 사용합니다.
테스트를 더 구체적으로 작성해야 하면 ex. loginMemberNameDuplicateException 이런 식으로 활용합니다.

**Comment by bperhaps** [comment]
회의에서 정하는걸루~

**Comment by da-nyee** [comment]
좋습니다 ~~!
