### ISSUE TITLE
프론트엔드에서 필요한 API 목록

### ISSUE THREAD

**Issue by soulgchoi** [woowacourse-moltudy/15-mins-retrospective#34]
- 회원가입&로그인 -> 응답으로 토큰 발급
- 토큰만 있는 빈 요청일 때 멤버 정보 응답
- 6시&10시 신청
- 6시&10시 삭제
- 6시&10시 신청한 멤버 목록 조회
- 페어 매칭 조회(한 번 매칭되면 계속 같은 결과)

**Comment by bperhaps** [comment]
페어 매칭 조회의 경우, 6~10시 사이에 요청시 6시 사람들, 10~다음날 6시 사이의 경우 10시 타임 사람들로 페어 만들면 될까요?

**Comment by soulgchoi** [comment]
> 페어 매칭 조회의 경우, 6~10시 사이에 요청시 6시 사람들, 10~다음날 6시 사이의 경우 10시 타임 사람들로 페어 만들면 될까요?

이거 무슨 말인지 다시 설명좀....🥲
