### ISSUE TITLE
entity의 불변, 가변 문제

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#35]
저번에 말했던 부분이 이 부분이었군요!
이부분에 대해서도 이슈등록 할게요! 저의 경우 특히나 이런 클래스의 경우 불변객체 취급이 필수적이라고 생각해서 final을 항상 붙이는 편이랍니다. 그렇게 되면 저번처럼 this에 null을 넘기는 방식의 구현이 될텐데, 이에 대한 컨벤션도 맞춰야 한다고 생각해요!

_Originally posted by @bperhaps in https://github.com/woowacourse-moltudy/15-mins-retrospective/pull/29#discussion_r649739566_

Entity라는 개념 자체가 DDD에서 튀어나왔으니 불편하더라도 제 생각을 한번 말해보겠습니다.

DDD에서 Entity는 가변이라고 정의하고 있습니다. Entity는 단순히 테이블과 매칭되는 객체 이전에, 비즈니스 로직을 가지는 객체거든요. 따라서 테이블의 어떤 데이터를 변경하고 싶다는 것은 Entity의 상태를 Entity가 가지고 있는 비즈니스 로직을  통해서 변경하는 행위를 의미하게 됩니다.
그리고 그 변경된 Entity를 Repository에 그대로 넣음으로써 JPA가 변경된 부분을 테이블에 반영해 주는 방식이구요.
이런 관점에서 봤을 때 Entity는 가변이어야 하지만, 우리가 알기로 객체는 불변성을 유지하는게 좋다고 들었습니다.

이 괴리감 어떻게 하실껀가요? 사실 저는 Entity 한정으로는 가변성이 좋다고 생각합니다. 불변성을 당연히 하고싶기는 하지만 성능성의 이슈가 클거라고 생각해요 (Entity의 크기가 커질 경우) 여러분의 의견이 궁금합니다!

**Comment by sihyung92** [comment]
엔튀튀
객체의 불변성은 객체 상태 변화에 의한 사이드 이펙트를 최소화하기 위한 거잖아요? 값 객체같은 경우 싸이드 이풱트를 최소화하는 방향으로 가는 게 맞다고 생각합니다. 그러나 엔뛰뛰를 자율적이라고 부르는 이유는,  본인이 가진 데이터의 상태(변할 수 있음)에 따라 본인의 행동을 스스로 결정할 수 있기 때문이라고 생각해요. 변하지 않는 상태로 동일한 행위만 하는 엔띠띠는 엔틔틔라기보단 퐝션 아닐까요?? 동작원리로 따져보면, 동일참조는 동일값을 반환하는 것이 불변의 실제 구현이잖아요? 엔ㅌㅌ는 equals를 오버라이드해 id로 동등비교를 하므로 변화한 상태마다 참조를 바꾸는 불변의 방식에서 이점을 얻을 수 없다고 생각합니다. jpa가 동일 id에는 아예 동일 참조 객체를 넘겨주는 것에도 이런 철학이 담겨있지 않나 싶네요(상태변화를 감지할 뿐 참조를 변경하진 않음)
 
불변이란 작은 제약으로 큰 장애를 방지한다는 김영한님 말이 생각이 나는데, 달리 말하면 불변도 제약이라고 생각합니다. 제약을 거는 것에는 그만큼의 효과가 있어야 할텐데, 불변성의 효과가 엔뚜이뚜이에겐 무용하다고 생각합니다.

**Comment by bperhaps** [comment]
@sihyung92 동감동감~~ 넘나 멋진말입니다~~

**Comment by bperhaps** [comment]
불변쪽 관점에서는 불변만든다구 상태변화를 시키지 말자는건 아니구 상태가 변한 불변객체 뱉자는 의견이었습니다~~
