### ISSUE TITLE
dao와 dto 패키지 위치

### ISSUE THREAD

**Issue by bperhaps** [woowacourse-moltudy/15-mins-retrospective#36]
dao는 infrastrucutre, dto는 presentation 레이어에 존재해야 합니다. 관련 커밋이 필요해 보입니다.

**Comment by pika96** [comment]
페키지 vs 패키지..?

**Comment by bperhaps** [comment]
패키지가 맞지............

**Comment by bperhaps** [comment]
이젠 진짜 오타확인 개빡시게 한다 맨날 놀림당하네

**Comment by sihyung92** [comment]
저희 현재 로직에선 클라이언트 <-> 뷰 간의 dto가 서비스까지 침투해서 부패방지계층으로도 쓰이고 있잖아용 dto를 application 계층에 두는건 어떤가요? 해당 방식의 장점으로는
1. 어플리케이션 계층 -> 프레젠테이션 계층에 대한 의존을 끊어줄 수 있습니다.
2. 그게 전부야~ 다른 이유는 없어~

**Comment by sihyung92** [comment]
다오 인프라는 찬성

**Comment by bperhaps** [comment]
@sihyung92 그래서 원론적으로는 클라 - 컨트롤러간의 dto, 컨트롤러 - 서비스 간의 dto를 따로 만들어줘야하는데 대부분은 그렇게 안하쥐... 
서비스에 dto를 두는건 영 아닌듯... 계층구조 관점이나 현재 dto의 사용 목적 관점이나...

**Comment by bperhaps** [comment]
자바블에 케빈이 잘 설명해놨었는데 읽어보면 좋을듯

**Comment by da-nyee** [comment]
미션은 View-Controller-Service 간 DTO를 넘기는 형태로 진행했는데요.
지난번에 [잊을만 하면 돌아오는 정산 신병들](https://woowabros.github.io/experience/2021/02/05/pilot-project-siyoung.html)을 읽고 View-Controller / Controller-Service 간 DTO를 분리하는 것의 장점을 이해했어요.
이번 프로젝트에서 이런 방식으로 구성해도 괜찮을 거 같습니다.

**Comment by da-nyee** [comment]
궁금한 게 있는데요.
왜 infrastructure에 DAO를 둬야 하나요?

**Comment by bperhaps** [comment]
@da-nyee infrastructure 레이어에 보통 서드파티 모듈들을 두는 편이에요. Dao같은 경우는 어플리케이션과 외부 영속성 모듈(h2, mysql)과의 연결역활을 해주는 어뎁터이기 때문에 infrastructure에 둡니다! 좀 더 자세히 알고싶으면 댓글 주세용 글이 길어질 것 같아서 여기까지만 쓸께요!
