### ISSUE TITLE
현재 시간과 요청 시간이 다른 문제

### ISSUE THREAD

**Issue by soulgchoi** [woowacourse-moltudy/15-mins-retrospective#67]
기능 오류 테스트 중에 
요청 당시 시간 6월 20일 2시 -> 실제 페어 매칭 요청 시간 2021-06-19 가 되는 문제 발견

**Comment by sihyung92** [comment]
아직 유효한 이슈인가요? AWS EC2 서버 시간이 다른걸 수도 있어서, 확인해볼게요

**Comment by sihyung92** [comment]
명령어 time으로 확인했고 timezone이 UTC로 잡혀있는 걸 확인해씀다
https://jhnyang.tistory.com/169 의거해서 was서버 타임존을 수정할게요

**Comment by sihyung92** [comment]
자바스크립트에서의 타임존은 뭐가 기준이 되는지 모르겠네요 유저의 OS시간이 기준이 될거 같긴한데, 뭔가 시간을 동기화 시켜주는 방법이 있을 것 같아요
